### PR TITLE
Adding saml2 support

### LINKED ISSUE #57: Error EPERM: Required library not found: `python3-saml`
A customer faced this issue

$ ceph dashboard sso show saml2
Error EPERM: Required library not found: `python3-saml`

Shunde found workaround that installing python3-onelogin-saml2 solves the issue.

###
sudo docker exec -it 5bc3cb129086 /bin/sh

apt update

apt install python3-onelogin-saml2

Restart the container:

sudo docker restart 5bc3cb129086

### PR DESCRIPTION
**Pull request by xtrusia**
Fixing below error by adding proper pkg

$ ceph dashboard sso show saml2
Error EPERM: Required library not found: `python3-saml`

Closes #57 

previous PR
https://github.com/canonical/ceph-containers/pull/58

### CODE REVIEW

**Comment by xtrusia** [comment]
@UtkarshBhatthere hey, this is blocked by #63 ? and it is also blocked by the other issues?
Thanks a lot for your working.

**Comment by UtkarshBhatthere** [comment]
I had raised 63 to check if pinning to an LTS LXD release fixes the build failures. It is not necessarily blocking (unless it fixes the build job). I have triggered reruns for jobs on this PR and on #63.

**Comment by xtrusia** [comment]
I see thanks. rook script https://github.com/rook/rook/blob/release-1.12/tests/scripts/github-action-helper.sh#L23
returns nothing
and try to wipefs with just '1'
I'm analyzing this why it is happening. if you have any advice, please let me know.

Thanks a lot.

**Comment by xtrusia** [comment]
not sure why rook script is not working(empty value) but if I copy them to this code, it works. (still has more issues after the test)

**Comment by UtkarshBhatthere** [comment]
@xtrusia I am pretty sure that the env disk layout changed and the bash script simply couldn't fetch required disk anymore. Good news is that I have removed the rockcraft-pack-action dependency and switched to rockcraft snap directly. We are able to build the rock, waiting for the cephadm test to pass.

**Pull request merged**
