### PR TITLE
Adding saml2 support

### LINKED ISSUE #57: Error EPERM: Required library not found: `python3-saml`
A customer faced this issue

$ ceph dashboard sso show saml2
Error EPERM: Required library not found: `python3-saml`

Shunde found workaround that installing python3-onelogin-saml2 solves the issue.

###
sudo docker exec -it 5bc3cb129086 /bin/sh

apt update

apt install python3-onelogin-saml2

Restart the container:

sudo docker restart 5bc3cb129086

### PR DESCRIPTION
**Pull request by xtrusia**
Fixing below error by adding proper pkg

$ ceph dashboard sso show saml2
Error EPERM: Required library not found: `python3-saml`

Closes #57

### CODE REVIEW

**Comment by UtkarshBhatthere** [comment]
Thanks @xtrusia, taking a look.

**Comment by UtkarshBhatthere** [comment]
@xtrusia can you please rebase your PR with main ? I have unblocked the cephadm CI tests, we should be able to get your PR merged with it.

**Comment by xtrusia** [comment]
@UtkarshBhatthere  thanks. I adjusted it. but it seems that still doesn't work yet?

**Comment by UtkarshBhatthere** [comment]
The CephadmTest passes which implies the change is OK. We still have not fixed the Rook tests yet.

**Comment by UtkarshBhatthere** [comment]
@xtrusia are all the commits in this PR not signed ? Github seems to be complaining about it.

**Pull request closed without merging**
